package jp.ikisaki.www.db;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by wangyouqi on 2015/05/29.
 */

@DatabaseTable
public class Classcode {

    // id is generated by the database and set on the object automagically
    @DatabaseField (id = true)
    int ID;
    @DatabaseField (index = true)
    int sector_ID;
    @DatabaseField
    String name;
    @DatabaseField
    String detail;

    public Classcode() {
        // needed by ormlite
    }
    public Classcode(String word) {

    }

    public int getId() {
        return ID;
    }
    public int getSector_ID() {
        return sector_ID;
    }
    public String getClasscode_name() {
        return name;
    }
    public String getClasscode_detail() {
        return detail;
    }
}