package jp.ikisaki.www.db;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by wangyouqi on 2015/05/29.
 */

@DatabaseTable
public class Landmark {

    // id is generated by the database and set on the object automagically
	@DatabaseField (generatedId = true, unique = true)
	int id;
	@DatabaseField //(columnName = "_word")
	String word;
    @DatabaseField
    int int_landmark_id;
    @DatabaseField
    String vc_landmark_name;
    @DatabaseField
    String vc_landmark_yomi;
    @DatabaseField
    String vc_landmark_type;
    @DatabaseField
    String vc_landmark_addr;
    @DatabaseField
    float f_landmark_fix;
    @DatabaseField
    float f_landmark_latitude;
    @DatabaseField
    float f_landmark_longitude;
    @DatabaseField
    int int_landmark_lat;
    @DatabaseField
    int int_landmark_lng;
    @DatabaseField
    String vc_landmark_figure;
    @DatabaseField
    String vc_landmark_link;
    @DatabaseField
    String tx_landmark_comment;
    //@DatabaseField(format="DATE_STRING")
    //Date dt_create_date;

	public Landmark() {
        // needed by ormlite
	}
    public Landmark(String word) {
        this.word = word;
    }

	public void setWord(String word) {
		this.word = word;
	}
    public String getWord() {
        return word;
    }

    public int get_landmark_id() {
        return int_landmark_id;
    }
    public String get_landmark_name() {
        return vc_landmark_name;
    }
    public String get_landmark_yomi() {
        return vc_landmark_yomi;
    }
    public String get_landmark_type() {
        return vc_landmark_type;
    }
    public String get_landmark_addr() {
        return vc_landmark_addr;
    }
    public float get_landmark_fix() {
        return f_landmark_fix;
    }
    public float get_landmark_latitude() {
        return f_landmark_latitude;
    }
    public float get_landmark_longitude() {
        return f_landmark_longitude;
    }
    public String get_landmark_figure() {
        return vc_landmark_figure;
    }
    public String get_landmark_link() {
        return vc_landmark_link;
    }
    public String get_landmark_comment() {
        return tx_landmark_comment;
    }
    public int get_landmark_lat() {
        return int_landmark_lat;
    }
    public int get_landmark_lng() {
        return int_landmark_lng;
    }

	@Override //重载 from parent
	public String toString() {
		StringBuilder sb = new StringBuilder();

		sb.append("id=").append(id);
		sb.append(" ,word=").append(word);
        sb.append(" ,vc_landmark_name=").append(vc_landmark_name);
        SimpleDateFormat dateFormatter = new SimpleDateFormat("MM/dd/yyyy HH:mm:ss.S");
        //sb.append(" ,dt_create_date=").append(dateFormatter.format(dt_create_date).toString());

        //System.out.println("logcat:55555555555:size=" + dt_create_date);
		return sb.toString();
	}
}