package jp.ikisaki.www.db;
import com.j256.ormlite.field.DatabaseField;
import com.j256.ormlite.table.DatabaseTable;
import java.text.SimpleDateFormat;
import java.util.Date;

/**
 * Created by wangyouqi on 2015/05/29.
 */

@DatabaseTable (tableName = "regdevice")
public class RegDevice {

    // id is generated by the database and set on the object automagically
    @DatabaseField
    String vc_device_serial;
    @DatabaseField
    int int_start_id;
    @DatabaseField
    String vc_start_name;

    public RegDevice() {
        // needed by ormlite
    }
    public RegDevice(String word) {

    }

    public String getVc_device_serial() {
        return vc_device_serial;
    }
    public int getInt_start_id() {
        return int_start_id;
    }
    public String getVc_start_name() {
        return vc_start_name;
    }

}
